FROM ubuntu:latest

RUN export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install -y curl python3 python3-pip python3-numpy python3-scipy \
    python3-matplotlib wget libboost-python-dev libboost-numpy-dev libboost-dev build-essential zlib1g-dev \
    libboost-system-dev libboost-program-options-dev
